### ISSUE TITLE
Project not building

### ISSUE THREAD

**Issue by alphabetalambda** [Rarisma/Simple-Server-Manager#3]
The project isn't building through github
I believe this is due to WPF only being able to be built on windows however it is setup to be built on ubuntu

**Comment by Rarisma** [comment]
Didn't mean to close this, 
thanks for the feedback,
Going to try and see if there is way to get github actions to build it on windows

**Comment by Rarisma** [comment]
fixed, just set up the normal recomended .net and changed ubuntu-latest to windows-latest, it seems to run now!
Thank you for raising this.
